import type { Metadata } from "next"
import { Source_Serif_4, JetBrains_Mono } from "next/font/google"
import "./globals.css"

import { ThemeProvider } from "next-themes"
import { Toaster } from '@/components/ui/sonner'
import SizeScreenHelper from '@/components/screensizehelper'
import ClerkProviderWithTheme from "@/components/providers/ClerkProviderWithTheme"

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "600", "700"],
  display: "swap",
})

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sourceSerif.variable} ${jetbrainsMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProviderWithTheme>
            {children}
            <Toaster position="top-center" expand />
            <SizeScreenHelper />
          </ClerkProviderWithTheme>
        </ThemeProvider>
      </body>
    </html>
  )
}
