import type { Metadata } from "next"
import { Source_Serif_4, JetBrains_Mono } from "next/font/google"
import "./globals.css"

import { ThemeProvider } from "next-themes"
import { ClerkProvider } from '@clerk/nextjs'
import { clerkAppearance } from '@/lib/clerk-theme'
import { esES } from '@clerk/localizations'
import { Toaster } from '@/components/ui/sonner'
import SizeScreenHelper from '@/components/screensizehelper'

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "600", "700"],
  display: "swap",
})

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={clerkAppearance} localization={esES}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${sourceSerif.variable} ${jetbrainsMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster position="top-center" expand />
            <SizeScreenHelper />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
